kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: '172.31.255.100' #IP VM CLUSTER
  KUBERNETES_SERVICE_PORT: '6443'